##############################################################################################################
# This tool calculates the Spherical Wave Expansion coefficients (Hansen) from a given E- and H-field        #
# and/or reconstructs an E- and H-field from given Qsmnc coefficients on a spherical grid                    #
# The code follows the notation of J.E. Hansen, "Spherical Near-Field Antenna Measurements"  (see README)    #
# ISBN (13 digit) 978-0-86341-110-6 / ISBN (10 digit) 0 86341 110 X                                          #
#                                                                                                            #
# The software was developed and tested with GNU Octave 10.3.0                                               #
# Compatibility with MATLAB has not been verified.                                                           #                                                                                  
# This implementation is currently in an early development stage (alpha version)                             #
# Currently, only outgoing waves (C=3) are supported                                                         #
# Development artifacts may still be present / Structures and function signatures might change in the future #
# No numerical stability or reliability checks have been implemented yet                                     #
# For import of field data or Qsmn see below (more comfortable import function follows)                      #
# Copyright (c) 2026 Pierre Dubois-dit-Bonclaude / Licensed under the MIT License                            #
##############################################################################################################

close all;
clear all;

pkg load gsl; # GSL package needed
cores=1 # If parallel computing is used the number of CPU cores can be set here -> PARALLEL package needed

f=1e9   # Set frequency in Hz
N=30;   # Set maximum degree of spherical wave functions | TICRA GRASP rule for maximum theoretical mode on minimum sphere(r0): N = k*r0 + max( 3.6*(kr0)^(1/3), 10)
C=3     # Outgoing wave-> currently only outgoing waves C=3 are supported!!
R=100;  # Set radius of the sphere to calculate the SWE
Pn=4*pi # Set reference power in W

taper=-12;      # Taper for the Gaussian Beam example
taper_angle=30; # Taper angle for the Gaussian Beam example

phys=gen_phys(f); # Calculates some frequency related physical properties (lambda,k) and returns a struct

# Generates a grid on a sphere to evaluate the SWE by choosing highest degree N of the spherical wave functions
# and 'cc' for Clenshaw-Curtis quadrature or 'gl' for Gauss-Legendre quadrature and returns struct
# By choosing 'cc' or 'gl' grid points are set to 2*N+1 in PHI and 2*N+2 ('cc') or N+1 ('gl') in THETA (currently fixed)
# - 'cc' includes poles in THETA=0 and THETA=PI and is equidistant in THETA
# - 'gl' doesn't include poles - not equidistant in THETA - but reduces the number of discretization points by a factor of 2
gr=gen_grid(N,'cc');

# Two examples are part of this code:
# - A near-field description of a dipole
# - A far-field description of a tapered Gaussian Beam of a complex point source linearly polarized in x
#   as defined in TICRA GRASP (Maxwell-consistent formulation) | imaginary displacement b in z-direction is stored in the struct
# Both definitions return a struct with the information required for further processing
# FOR IMPORT: Generate a grid as described. Generate your E- and H-Field in full sph. components on this grid.
# Bring it into the struct form generated by the example dipole_near.m

dp=dipole_near(R,phys,gr);
gb=gaussian_far(taper , taper_angle , R , phys, gr);

# Power normalization to the power Pn | (4*pi Watt is used in TICRA GRASP for feeds but Pn can in general be chosen freely)
# 'power_norm' returns the normalised field and the Normalization constant in the struct
gbn=power_norm(gb,Pn);
dpn=power_norm(dp,Pn);

# Integration needed for the calculation of one side of the equation to find the Qsmnc coefficients (see 'README')
# Parallel Computing ('para') or Blocking ('block') can be chosen as computation methods
Int_smnc = Integration(N, phys, gr, gb,C,R,'block',cores);

# Computing the coefficients Q
Q=solve_eqs(Int_smnc,C,R,phys,gr);

# Watch the mode power map in N-M-space
h=mode_viewer(Q);

# Modify the calculated mode coefficients for reconstruction:
# Numerical noise will have an impact on reconstruction, therefore a threshold should be chosen!
# Power normalization might also be done in the mode space as in this example:
Q2=Q;
Q2(abs(Q2)<1e-10)=0; # Set threshold
Q2=power_norm(Q2,Pn);


# Choose parameters for reconstruction
# The grid size can be chosen freely according to the definitions 'cc' and 'gl'
# For reconstruction, N does not affect the SWE itself and is only used to choose more or fewer grid points
R=100
N=100
gr2=gen_grid(N,'cc');

# Reconstruct the field from the coefficients Qsmnc on a chosen grid using Blocking ('block') or
# Parallel Computing ('para') for minimum calculation time
# FOR IMPORT: Q has the dimension SxMxN as currently only C=3 is supported, it will have the dimension 2 x (2N+1) x N
# This means that Q is always the full set of coeffs defined by the maximum of N even if the Q's are zeros
# S=1:2 M=-N:1:N N=1:N  ->the M-dimension starts with M=-N=(index 1) and runs up to M=N (index end)
gb_rec=make_field(Q2,R,C,phys,gr2,'block',cores);

# Get the power (and radial Poynting component) of the field and add it to the structure
gb_recP=get_power2(gb_rec,gb_rec.grid);

# Compare two field directivity functions where the first argument is the Original (ORIG)
# and the second argument is the Reconstructed field (RECON)
# The directivity function is plotted on a linear scale when negative values appear (often in the near-field)
field_viewer(gbn,gb_recP);

# Notes:
# -Numerical stability is currently neither checked automatically nor reported by error messages.
# -If no pattern is visible in the field_viewer the selected parameters probably led to numerical issues.
#  This often happens when N is high and k*R is low (near-field) in analyses as well as in reconstruction.
# -If no lower threshold is applied to Q this may lead to artifacts depending on the other settings



